# -*- coding: utf-8 -*-
"""data_cleaning_analysis_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OaOVVvCIbUqunYTFUVj4UL8xAub65aQQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


plt.style.use('default')

orders = pd.read_csv("/content/olist_orders_dataset.csv")
customers = pd.read_csv("/content/olist_customers_dataset.csv")

print("Orders Data:")
print(orders.head())
print(orders.info())
print(orders.isnull().sum())


print("\nCustomers Data:")
print(customers.head())
print(customers.info())
print(customers.isnull().sum())

orders['order_purchase_timestamp'] = pd.to_datetime(
    orders['order_purchase_timestamp']
)

orders.drop_duplicates(inplace=True)
customers.drop_duplicates(inplace=True)

orders = orders.dropna()
customers = customers.dropna()

orders.columns = orders.columns.str.lower()
customers.columns = customers.columns.str.lower()

df = pd.merge(
    orders,
    customers,
    on="customer_id",
    how="left"
)

df['order_year'] = df['order_purchase_timestamp'].dt.year
df['order_month'] = df['order_purchase_timestamp'].dt.month
df['order_day'] = df['order_purchase_timestamp'].dt.day

customers_orders = df.groupby('customer_id')['order_id'].count().reset_index()
customers_orders.columns = ['customer_id', 'total_orders']

yearly_orders = df.groupby('order_year')['order_id'].count()
print(yearly_orders)

monthly_orders = df.groupby('order_month')['order_id'].count()
print(monthly_orders)

top_cities = df['customer_city'].value_counts().head(10)
print(top_cities)

customer_freq = df.groupby('customer_id')['order_id'].count()

repeat_customers = customer_freq[customer_freq > 1].count()
new_customers = customer_freq[customer_freq == 1].count()

print("Repeat Customers:", repeat_customers)
print("New Customers:", new_customers)

monthly_growth = monthly_orders.pct_change()

plt.figure(figsize=(10,5))
monthly_orders.plot(marker='o')
plt.title("Monthly Orders Trend")
plt.xlabel("Month")
plt.ylabel("Orders")
plt.show()

monthly_year = df.groupby(['order_year', 'order_month'])['order_id'].count().reset_index()

plt.figure(figsize=(10,5))
sns.lineplot(data=monthly_year, x='order_month', y='order_id', hue='order_year')
plt.title("Monthly Orders by Year")
plt.show()

plt.figure(figsize=(10,5))
top_cities.plot(kind='bar')
plt.title("Top 10 Cities by Orders")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(customer_freq, bins=30)
plt.title("Customer Purchase Frequency")
plt.show()

plt.figure(figsize=(10,5))
monthly_growth.plot()
plt.title("Monthly Growth Rate")
plt.show()

plt.figure(figsize=(8,6))
sns.heatmap(df.select_dtypes(include=np.number).corr(), annot=True)
plt.title("Correlation Matrix")
plt.show()

"""1. Orders show clear seasonal trends with certain month having higher asctivity.
2. A few cities dominate total orders, indicating geographic contration.
3. Most customers are one-time buyers, showing low retention.
4. Repeat customers are fewer but more valuable.
5. growth rate fluctuates, indicating unstable demand patterns.
6. Business should focus on retention and high-performing regions.
"""

df.to_csv("cleaned_olist_data.csv", index=False)

from IPython.display import FileLink
FileLink('cleaned_olist_data.csv')